/* eslint-disable prettier/prettier */
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const mockData = [
{"id":1,"name":"6년근고려홍삼정스틱","brand":null},
{"id":2,"name":"마그네슘정","brand":null},
{"id":3,"name":"비타민D 1000IU","brand":null},
{"id":4,"name":"비타민D 1000IU VitaminD 1000IU","brand":null},
{"id":5,"name":"비타민D 1000IU 츄어블","brand":null},
{"id":6,"name":"비타민D 1000Q연질캡슐","brand":null},
{"id":7,"name":"비타민D 1080 IU","brand":null},
{"id":8,"name":"비타민D 1099IU","brand":null},
{"id":9,"name":"비타민D 2000","brand":null},
{"id":10,"name":"비타민D 2000 I.U","brand":null},
{"id":11,"name":"비타민D 2000 IU","brand":null},
{"id":12,"name":"비타민D 2000I.U 연질캅셀","brand":null},
{"id":13,"name":"비타민D 2000IU 골드","brand":null},
{"id":14,"name":"비타민D 2000IU 볼란테","brand":null},
{"id":15,"name":"비타민D 2000IU 츄어블","brand":null},
{"id":16,"name":"비타민D 2000IU 키즈","brand":null},
{"id":17,"name":"비타민D 2000IU(Vitamin D 2000IU)","brand":null},
{"id":18,"name":"비타민D 2000IU(전량수출용)","brand":null},
{"id":19,"name":"비타민D 3000 & 마그네슘(Mg)","brand":null},
{"id":20,"name":"비타민D 4000IU 골드","brand":null},
{"id":21,"name":"비타민D 400IU(수출용)","brand":null},
{"id":22,"name":"비타민D 500IU","brand":null},
{"id":23,"name":"비타민D 50ug","brand":null},
{"id":24,"name":"비타민D 600","brand":null},
{"id":25,"name":"비타민D 600 플러스","brand":null},
{"id":26,"name":"비타민D 600IU","brand":null},
{"id":27,"name":"커스텀바이오키즈유산균앤아연","brand":null},
{"id":28,"name":"커스텀바이오패밀리프로바이오틱스","brand":null},
{"id":29,"name":"커스텀바이오프리바이오틱스앤아연","brand":null},
{"id":30,"name":"커커비타민","brand":null},
{"id":31,"name":"커클랜드 시그니춰 데일리 멀티비타민&미네랄","brand":"뉴트리라이트"},
{"id":32,"name":"커클랜드 시그니춰 실버 멀티비타민&미네랄","brand":"뉴트리라이트"},
{"id":33,"name":"커트 큐브","brand":null},
{"id":34,"name":"커트그램 더라스트핏","brand":null},
{"id":35,"name":"커트그램엔딩컷","brand":null},
{"id":36,"name":"커피맛 다이어트","brand":null},
{"id":37,"name":"컨디션 리버","brand":null},
{"id":38,"name":"컨디션 멀티","brand":null},
{"id":39,"name":"컨디션 비 컴플렉스","brand":null},
{"id":40,"name":"컨디션 우먼","brand":null},
{"id":41,"name":"컨디션 조인트","brand":null},
{"id":42,"name":"컨디션 프로바이오","brand":null},
{"id":43,"name":"컨트롤 S에스","brand":null},
{"id":44,"name":"컨트롤 식이섬유&멀티비타민&미네랄","brand":null},
{"id":45,"name":"컨트롤500","brand":null},
{"id":46,"name":"컨트롤난소화성말토덱스트린","brand":null},
{"id":47,"name":"컨트롤지G","brand":null},
{"id":48,"name":"컨트롤화이버","brand":null},
{"id":49,"name":"컬러티 다이어트 그린 COLORTEA DIET GREEN","brand":null},
{"id":50,"name":"컬러티 다이어트 레드 COLORTEA DIET RED","brand":null},
{"id":51,"name":"컬러티 다이어트 브라운 COLORTEA DIET BROWN","brand":null},
{"id":52,"name":"컬러티 다이어트 블랙 COLORTEA DIET BLACK","brand":null},
{"id":53,"name":"컬러푸드 멀티비타민 22종","brand":null},
{"id":54,"name":"컬러풀 비타민C","brand":null},
{"id":55,"name":"컬쳐럴 안티바이오틱 써포트(Culturelle Antibiotic Support)","brand":null},
{"id":56,"name":"코스맥스엔비티 프로바이오틱스","brand":null},
{"id":57,"name":"코스맥스엔비티 홍삼정","brand":null},
{"id":58,"name":"코스맥스엔비티 홍삼진액","brand":null},
{"id":59,"name":"코스메힐 헬씨 화이트 에퍼글로우","brand":null},
{"id":60,"name":"코스바디 프로바이오틱스 프리미엄","brand":null},
{"id":61,"name":"코스밸런스 멀티비타민&미네랄","brand":null},
{"id":62,"name":"코스밸런스 밀크씨슬 프리미엄","brand":null},
{"id":63,"name":"코스밸런스 칼슘마그네슘&비타민D","brand":null},
{"id":64,"name":"코스트코 커클랜드 액티브 비타민팩","brand":"뉴트리라이트"},
{"id":65,"name":"코알라비트멀티비타민","brand":null},
{"id":66,"name":"코알라팔스 생생 유산균 딸기맛","brand":null},
{"id":67,"name":"코알라팔스 생생 유산균 요거트맛","brand":null},
{"id":68,"name":"코알라팔스 생생 유산균 포도맛","brand":null},
{"id":69,"name":"코알라팔스 홍삼젤리 딸기맛 ","brand":null},
{"id":70,"name":"코어 신바이오틱스 프리바이오틱스 프로바이오틱스","brand":null},
{"id":71,"name":"코어 프로틴 플러스","brand":null},
{"id":72,"name":"코어 프로틴 플러스 식이섬유","brand":null},
{"id":73,"name":"코어 프리바이오틱스 FOS(에프오에스)","brand":null},
{"id":74,"name":"코어셀렉트이뮨","brand":null},
{"id":75,"name":"코어업","brand":null},
{"id":76,"name":"코어진스 농축액(COREGINS EXTRACT) / (전량수출용)","brand":null},
{"id":77,"name":"코어진스 타블렛(COREGINS TABLETS)","brand":null},
{"id":78,"name":"코어팩 포 우먼","brand":null},
{"id":79,"name":"코엔자임 50mg","brand":null},
{"id":80,"name":"코엔자임 Q10","brand":null},
{"id":81,"name":"코엔자임 볼란테","brand":null},
{"id":82,"name":"코엔자임 큐텐 해피원","brand":null},
{"id":83,"name":"코엔자임NatQ","brand":null},
{"id":84,"name":"코엔자임Q10 레벨업","brand":null},
{"id":85,"name":"코엔자임Q10 캡슐","brand":null},
{"id":86,"name":"코엔자임Q10골드","brand":null},
{"id":87,"name":"코엔자임Q10파워","brand":null},
{"id":88,"name":"코엔자임Q10플러스골드","brand":null},
{"id":89,"name":"코엔자임Q10항산화플러스","brand":null},
{"id":90,"name":"코엔자임멀티비타민 (수출용)","brand":null},
{"id":91,"name":"코엔자임큐텐 50mg","brand":null},
{"id":92,"name":"코엔자임큐텐 Co-Q-10","brand":null},
{"id":93,"name":"코엔자임큐텐 리턴","brand":null},
{"id":94,"name":"코엔자임큐텐 프리미엄","brand":null},
{"id":95,"name":"코엔자임큐텐 플러스","brand":null},
{"id":96,"name":"코엔자임큐텐맥스100mg","brand":null},
{"id":97,"name":"코엔자임큐텐포유","brand":null},
{"id":98,"name":"코엔자임큐텐플러스","brand":null},
{"id":99,"name":"코엔자임플러스","brand":null},
{"id":100,"name":"코오롱 N-아세틸글루코사민","brand":null},
{"id":101,"name":"코오롱 루테인 아스타잔틴","brand":null},
{"id":102,"name":"코오롱 밀크씨슬","brand":null},
{"id":103,"name":"코오롱 알티지오메가3 1100","brand":null},
{"id":104,"name":"코오롱 칼마디아","brand":null},
{"id":105,"name":"코오롱 프로바이오틱스","brand":null},
{"id":106,"name":"코오롱 프로바이오틱스 장용캡슐","brand":null},
{"id":107,"name":"코오롱리얼비타민C 1000","brand":null},
{"id":108,"name":"코오롱리얼비타민C 프리미엄","brand":null},
{"id":109,"name":"코오롱제약 아이&오메가3","brand":"뉴트리라이트"},
{"id":110,"name":"코오롱츄어블비타민C레드비타","brand":null},
{"id":111,"name":"코오롱츄어블비타민C블루비타","brand":null},
{"id":112,"name":"코오롱츄어블비타민C옐로우비타","brand":null},
{"id":113,"name":"코제소프트","brand":null},
{"id":114,"name":"코제플러스","brand":null},
{"id":115,"name":"코준","brand":null},
{"id":116,"name":"코카암비타","brand":null},
{"id":117,"name":"코케어","brand":null},
{"id":118,"name":"코코몽 멀티비타","brand":null},
{"id":119,"name":"코코몽 튼튼칼슘 츄잉정","brand":null},
{"id":120,"name":"코코몽 홍삼키즈 쑥쑥","brand":null},
{"id":121,"name":"코코몽키즈오메가","brand":"일양약품"},
{"id":122,"name":"코큐넥신","brand":null},
{"id":123,"name":"코큐메가","brand":null},
{"id":124,"name":"코큐비","brand":null},
{"id":125,"name":"코큐비타","brand":null},
{"id":126,"name":"코큐에이스","brand":null},
{"id":127,"name":"코큐텐 ","brand":null},
{"id":128,"name":"코큐텐 100mg ACE 플러스","brand":null},
{"id":129,"name":"코큐텐 100mg 맥스","brand":null},
{"id":130,"name":"코큐텐 ACE 플러스","brand":null},
{"id":131,"name":"코큐텐 멀티12","brand":null},
{"id":132,"name":"코큐텐 포르테","brand":null},
{"id":133,"name":"코큐텐 프리미엄 ","brand":null},
{"id":134,"name":"코큐텐 하트캡슐","brand":null},
{"id":135,"name":"코큐텐100mg비타민A,B,C,E,셀레늄","brand":null},
{"id":136,"name":"코큐텐ACE(전량수출용)","brand":null},
{"id":137,"name":"코큐텐ACE+","brand":null},
{"id":138,"name":"코큐텐B연질캡슐","brand":null},
{"id":139,"name":"코큐텐-C","brand":null},
{"id":140,"name":"코큐텐뉴스","brand":null},
{"id":141,"name":"코큐텐밸런스 츄어블","brand":null},
{"id":142,"name":"코큐텐비","brand":null},
{"id":143,"name":"코큐텐비타","brand":null},
{"id":144,"name":"코큐텐비타민씨플러스9","brand":null},
{"id":145,"name":"코큐텐빅파워","brand":null},
{"id":146,"name":"코큐텐알파","brand":null},
{"id":147,"name":"코큐텐에이스프리미엄","brand":null},
{"id":148,"name":"코큐텐오메가3","brand":null},
{"id":149,"name":"코큐텐오메가플러스","brand":null},
{"id":150,"name":"코큐텐프리미엄씨","brand":null},
{"id":151,"name":"코큐텐플러스비타민","brand":null},
{"id":152,"name":"코큐텐플러스아연","brand":null},
{"id":153,"name":"코큐텐플러스오메가쓰리","brand":null},
{"id":154,"name":"코크린","brand":null},
{"id":155,"name":"키즈비타멀티","brand":null},
{"id":156,"name":"키즈비타민","brand":null},
{"id":157,"name":"키즈비타민A젤리","brand":null},
{"id":158,"name":"키즈비타민C+아연, B2","brand":null},
{"id":159,"name":"키즈비타씨(딸기맛)","brand":null},
{"id":160,"name":"키즈비타씨(베트남수출용)","brand":null},
{"id":161,"name":"키즈비타씨(복숭아맛)","brand":null},
{"id":162,"name":"키즈비타씨(복숭아맛,딸기맛)","brand":null},
{"id":163,"name":"키즈비타씨(포도맛)","brand":null},
{"id":164,"name":"키즈비타칼슘마그네슘","brand":null},
{"id":165,"name":"키즈사랑프로바이오틱스","brand":null},
{"id":166,"name":"키즈스타","brand":null},
{"id":167,"name":"키즈식물성오메가","brand":null},
{"id":168,"name":"키즈쑥쑥 칼슘 플러스 ","brand":null},
{"id":169,"name":"키즈쑥쑥홍삼젤리","brand":null},
{"id":170,"name":"키즈아연","brand":null},
{"id":171,"name":"키즈아연 + 비타민C,E ","brand":null},
{"id":172,"name":"키즈아연+종합비타민","brand":null},
{"id":173,"name":"키즈아연비타민D","brand":null},
{"id":174,"name":"키즈아연젤리","brand":null},
{"id":175,"name":"키즈아이","brand":null},
{"id":176,"name":"키즈아이솔루션\t	","brand":null},
{"id":177,"name":"키즈아이쑥쑥","brand":null},
{"id":178,"name":"키즈아이쑥쑥골드","brand":null},
{"id":179,"name":"키즈아이쑥쑥플러스","brand":null},
{"id":180,"name":"키즈알포홍삼큐골드","brand":null},
{"id":181,"name":"키즈액션멀티비타민미네랄","brand":null},
{"id":182,"name":"키즈액티브","brand":null},
{"id":183,"name":"키즈앤굿 홍삼면역젤리스틱","brand":null},
{"id":184,"name":"키즈업 쥬니어","brand":null},
{"id":185,"name":"키즈업베이비생유산균","brand":null},
{"id":186,"name":"키즈업베이비유산균","brand":null},
{"id":187,"name":"키즈업플러스","brand":null},
{"id":188,"name":"키즈오메가","brand":null},
{"id":189,"name":"키즈오메가3","brand":null},
{"id":190,"name":"키즈오메가-3츄어블","brand":null},
{"id":191,"name":"키즈오키어린이홍삼","brand":null},
{"id":192,"name":"키즈올리고","brand":null},
{"id":193,"name":"키즈요거틱스","brand":null},
{"id":194,"name":"키즈원 골드비","brand":null},
{"id":195,"name":"키즈원 골드지","brand":null},
{"id":196,"name":"키즈월드","brand":null},
{"id":197,"name":"키즈웰홍삼","brand":null},
{"id":198,"name":"키즈유산균락토(전량수출용)","brand":null},
{"id":199,"name":"키즈조아 1단계","brand":null},
{"id":200,"name":"키즈조아 2단계","brand":null},
{"id":201,"name":"키즈종합비타프리미엄","brand":null},
{"id":202,"name":"키즈징크락토","brand":null},
{"id":203,"name":"키즈징크시럽","brand":null},
{"id":204,"name":"키즈징크파우더","brand":null},
{"id":205,"name":"키즈츄어블","brand":null},
{"id":206,"name":"키즈츄어블멀티비타민","brand":null},
{"id":207,"name":"키즈츄어블멀티비타민&미네랄","brand":null},
{"id":208,"name":"키즈츄어블비타민 ","brand":null},
{"id":209,"name":"키즈츄어블아연위드비타민","brand":null},
{"id":210,"name":"키즈츄어블오메가3","brand":null},
{"id":211,"name":"키즈츄어블철분 플러스","brand":null},
{"id":212,"name":"키즈츄어블프로바이오틱스","brand":null},
{"id":213,"name":"키즈칼디","brand":null},
{"id":214,"name":"키즈칼디포르테","brand":null},
{"id":215,"name":"키즈칼슘","brand":null},
{"id":216,"name":"키즈칼슘마그네슘디","brand":null},
{"id":217,"name":"키즈커즈생유산균","brand":null},
{"id":218,"name":"키즈케어비타프로바이오틱스","brand":null},
{"id":219,"name":"키즈텐","brand":null},
{"id":220,"name":"키즈텐플러스+","brand":null},
{"id":221,"name":"키즈튼튼 멀티비타민 ","brand":null},
{"id":222,"name":"키즈튼튼 종합비타민&미네랄","brand":null},
{"id":223,"name":"키즈튼튼 칼슘&비타민D","brand":null},
{"id":224,"name":"키즈튼튼 홍삼젤리","brand":null},
{"id":225,"name":"탐란바이탈리티파인오일(TAMLAN vitality pine oil)","brand":null},
{"id":226,"name":"탐란바이탈포스파인오일(TAMLAN vital force pine oil)","brand":null},
{"id":227,"name":"탐란비타콜라겐(TAMLAN vita collagen)","brand":null},
{"id":228,"name":"탐란비타콜라겐(TAMLAN vita collagen)(전량수출용)","brand":null},
{"id":229,"name":"탐미유 밀크씨슬 프로바이오틱스","brand":null},
{"id":230,"name":"탐미유비타민C","brand":null},
{"id":231,"name":"탑 엔오에스 엠에스엠","brand":null},
{"id":232,"name":"탑바디 브이-투","brand":null},
{"id":233,"name":"탑칼슘마그네슘골드","brand":null},
{"id":234,"name":"탑클래스 루테인 플러스","brand":null},
{"id":235,"name":"태국용혼합유산균","brand":null},
{"id":236,"name":"태권동자","brand":null},
{"id":237,"name":"태권브이 슈퍼 리버아이(Taekwon V Super Liver Eye)","brand":null},
{"id":238,"name":"태권튼튼홍삼젤리(전량수출용)","brand":null},
{"id":239,"name":"태극삼농축액","brand":null},
{"id":240,"name":"태극삼농축액프리미엄","brand":null},
{"id":241,"name":"태극삼분말","brand":null},
{"id":242,"name":"태극삼액정","brand":null},
{"id":243,"name":"태극유산균","brand":null},
{"id":244,"name":"태비홍","brand":null},
{"id":245,"name":"태웅글루코사민","brand":null},
{"id":246,"name":"태웅이랑 튼튼쑥쑥","brand":null},
{"id":247,"name":"태웅프로폴리스","brand":null},
{"id":248,"name":"태웅활력홍삼","brand":null},
{"id":249,"name":"태자삼","brand":null},
{"id":250,"name":"태자삼 주니어","brand":null},
{"id":251,"name":"태홍란","brand":null},
{"id":252,"name":"태황력","brand":null},
{"id":253,"name":"터치다이어트 데이","brand":null},
{"id":254,"name":"턴유슬림","brand":null},
{"id":255,"name":"테디촌테디베어 프로바이오틱스 키즈","brand":null},
{"id":256,"name":"테라뮨 이뮨베타","brand":null},
{"id":257,"name":"테라지","brand":null},
{"id":258,"name":"테라타민","brand":"풀무원 로하스"},
{"id":259,"name":"테라트리 엠에스엠","brand":null},
{"id":260,"name":"테라프로바 패밀리","brand":null},
{"id":261,"name":"테라프로바 패밀리 프리미엄","brand":null},
{"id":262,"name":"테라프로폴리스17","brand":null},
{"id":263,"name":"테르엔 홍삼스틱","brand":null},
{"id":264,"name":"테민씨","brand":null},
{"id":265,"name":"테아닌과 밀크씨슬 활력솔루션","brand":null},
{"id":266,"name":"테아닌알파","brand":null},
{"id":267,"name":"테이크핏 엔더블유피아이 곡물맛","brand":null},
{"id":268,"name":"테일러푸룬맛다이어트젤리","brand":null},
{"id":269,"name":"테트라멀티비타민","brand":null},
{"id":270,"name":"텐더스 멀티비타민 포 레이디","brand":null},
{"id":271,"name":"텐텐 츄정","brand":"뉴트리라이트"},
{"id":272,"name":"텐프로텐","brand":null},
{"id":273,"name":"텐프로텐365","brand":null},
{"id":274,"name":"토날린 다이어트 CLA","brand":null},
{"id":275,"name":"토날린 블랙 짚","brand":null},
{"id":276,"name":"토날린 블랙짚 익스트림 맥스 맨","brand":null},
{"id":277,"name":"토날린 블랙짚 익스트림 맥스 우먼","brand":null},
{"id":278,"name":"토날린CLA플러스골드","brand":null},
{"id":279,"name":"토노 베타카로틴","brand":null},
{"id":280,"name":"토노겐(TONOGEN)(전량수출용)","brand":null},
{"id":281,"name":"토닉Q7","brand":null},
{"id":282,"name":"토닉큐","brand":null},
{"id":283,"name":"토라키즈","brand":null},
{"id":284,"name":"토라타민","brand":null},
{"id":285,"name":"토라타민-B","brand":null},
{"id":286,"name":"토라타민-F","brand":null},
{"id":287,"name":"토라타민에프(F)","brand":null},
{"id":288,"name":"토라토라-지(G)","brand":null},
{"id":289,"name":"토리든 다이어트 맨","brand":null},
{"id":290,"name":"토리스(비타민C)/감귤맛(수출용)","brand":null},
{"id":291,"name":"토리스(비타민C)/복숭아맛(수출용)","brand":null},
{"id":292,"name":"토마스와 홍삼친구 스마트","brand":null},
{"id":293,"name":"토마스와친구들 맛있는멀티비타민","brand":null},
{"id":294,"name":"토마스와친구들프리미엄칼슘 멀티비타민&미네랄","brand":null},
{"id":295,"name":"토마스와홍삼친구","brand":null},
{"id":296,"name":"토마토라이코펜&베타카로틴","brand":null},
{"id":297,"name":"토마토라이코펜골드","brand":null},
{"id":298,"name":"토백이 名(명) 홍삼농축액","brand":null},
{"id":299,"name":"토비코비타-딸기맛","brand":null},
{"id":300,"name":"토비코비타-복숭아맛","brand":null},
{"id":301,"name":"토비코비타-포도맛","brand":null},
{"id":302,"name":"토비테인","brand":null},
{"id":303,"name":"토비테인지아잔틴","brand":null},
{"id":304,"name":"토코페롤비타민E","brand":null},
{"id":305,"name":"토코하급수정","brand":null},
{"id":306,"name":"토코하급수타블렛","brand":null},
{"id":307,"name":"토코한국보건영","brand":null},
{"id":308,"name":"토탈이너뷰티","brand":null},
{"id":309,"name":"토탈케어 50+","brand":null},
{"id":310,"name":"토탈케어 멀티비타민 츄어블","brand":null},
{"id":311,"name":"톡!톡! 어린이 습관","brand":null},
{"id":312,"name":"톡톡 비타민C","brand":null},
{"id":313,"name":"톡톡 비타민D 드롭","brand":null},
{"id":314,"name":"톡톡 빠져라","brand":null},
{"id":315,"name":"톡톡 생유산균 드롭","brand":null},
{"id":316,"name":"톡톡 키드 생유산균","brand":null},
{"id":317,"name":"톡톡1","brand":null},
{"id":318,"name":"톡톡2","brand":null},
{"id":319,"name":"톡톡C","brand":null},
{"id":320,"name":"톡톡상큼비타민","brand":null},
{"id":321,"name":"톡톡아이오메가3","brand":null},
{"id":322,"name":"톡톡지움다이어트","brand":null},
{"id":323,"name":"톡톡큐골드","brand":null},
{"id":324,"name":"톡톡튼튼칼슘","brand":null},
{"id":325,"name":"톡톡하니DHA츄어블","brand":null},
{"id":326,"name":"톨차일드(전량수출용)","brand":null},
{"id":327,"name":"톨키드(TALL KID)(전량수출용)","brand":null},
{"id":328,"name":"톨플러스 홍삼유산균(전량수출용)","brand":null},
{"id":329,"name":"통(通)관절마디케어","brand":null},
{"id":330,"name":"통라이프 레드 2 다이어트 토날린CLA","brand":null},
{"id":331,"name":"통라이프 레드 4 다이어트 가르시니아","brand":null},
{"id":332,"name":"통라이프 로얄 프로폴리스골드","brand":null},
{"id":333,"name":"통라이프 멀티비타민골드","brand":null},
{"id":334,"name":"통라이프 비타민ACE+셀렌+아연","brand":null},
{"id":335,"name":"통라이프 키즈종합비타민ABCDE+미네랄+칼슘","brand":null},
{"id":336,"name":"통라이프 하이칼슘+마그네슘+비타민D+K","brand":null},
{"id":337,"name":"통엔","brand":null},
{"id":338,"name":"통엔F","brand":null},
{"id":339,"name":"통엔에프(F)","brand":null},
{"id":340,"name":"통쾌력","brand":null},
{"id":341,"name":"통쾌변","brand":null},
{"id":342,"name":"통쾌한 면역","brand":null},
{"id":343,"name":"통쾌한 유산균","brand":null},
{"id":344,"name":"통쾌한 장(腸)","brand":null},
{"id":345,"name":"통큰 프로바이오틱스 생(生)유산균","brand":null},
{"id":346,"name":"통큰 프리미엄 종합비타민","brand":null},
{"id":347,"name":"통큰 프리미엄 프로폴리스","brand":null},
{"id":348,"name":"통큰홍삼정","brand":null},
{"id":349,"name":"투 퍼 데이 캡슐 Two-per-day Capsules","brand":"라이프 익스텐션"},
{"id":350,"name":"투 퍼 데이 태블릿 Two-Per-Day Tablets","brand":"라이프 익스텐션"},
{"id":351,"name":"투데이 홍삼스틱","brand":null},
{"id":352,"name":"투데이 홍삼정","brand":null},
{"id":353,"name":"투데이홍삼정플러스","brand":null},
{"id":354,"name":"투컷 가르시니아녹차다이어트","brand":null},
{"id":355,"name":"트루화이바","brand":null},
{"id":356,"name":"트리마토-엘 플러스","brand":null},
{"id":357,"name":"트리맥스바이오틱스","brand":null},
{"id":358,"name":"트리벨셀렌효모","brand":"유한메디카"},
{"id":359,"name":"트리어드 DHA(TRIAD DHA)","brand":null},
{"id":360,"name":"트리어드 EPA(TRIAD EPA)","brand":null},
{"id":361,"name":"트리어드 그린 (Triad Green)","brand":null},
{"id":362,"name":"트리어드 오메가3 스테디(TRIAD Omega3 Steady)","brand":null},
{"id":363,"name":"트리어드 코어(TRIAD Core)","brand":null},
{"id":364,"name":"트리엔 셀렌효모비타","brand":null},
{"id":365,"name":"트리엔 엘코민비타민","brand":null},
{"id":366,"name":"트리엔 칼슘마그네슘","brand":null},
{"id":367,"name":"트리엔바이트Ⅱ","brand":null},
{"id":368,"name":"트리엔철","brand":null},
{"id":369,"name":"트리조인스타","brand":null},
{"id":370,"name":"트리콜다운","brand":null},
{"id":371,"name":"트리팩트나이트","brand":null},
{"id":372,"name":"트리팩트데이","brand":null},
{"id":373,"name":"트리포스3","brand":null},
{"id":374,"name":"트리플 2-에스에이치","brand":null},
{"id":375,"name":"트리플 다이어트","brand":null},
{"id":376,"name":"트리플 다이어트 가르시니아","brand":null},
{"id":377,"name":"트리플 더블 에이스","brand":null},
{"id":378,"name":"트리플 디펜스 비타민C","brand":null},
{"id":379,"name":"트리플 로얄 B","brand":null},
{"id":380,"name":"트리플 마그네슘","brand":null},
{"id":381,"name":"트리플 멀티 액션","brand":null},
{"id":382,"name":"트리플 바이오틱스","brand":null},
{"id":383,"name":"트리플 비타민C1000","brand":null},
{"id":384,"name":"트리플 슬림 다이어트","brand":null},
{"id":385,"name":"트리플 아이 프로텍터","brand":null},
{"id":386,"name":"트리플 업 젤리(Triple Up Jelly)","brand":null},
{"id":387,"name":"트리플 에센스 포맨","brand":null},
{"id":388,"name":"트리플 오메가3 멀티비타민미네랄","brand":null},
{"id":389,"name":"트리플 웰(Triple Well)(전량수출용)","brand":null},
{"id":390,"name":"트리플 칼마디","brand":null},
{"id":391,"name":"트리플 혈 케어플러스","brand":null},
{"id":392,"name":"트리플 홍삼농축액","brand":null},
{"id":393,"name":"트리플S","brand":null},
{"id":394,"name":"트리플다이어트","brand":null},
{"id":395,"name":"트리플락토 베이비","brand":null},
{"id":396,"name":"트리플락토 키즈","brand":null},
{"id":397,"name":"트리플러스","brand":null},
{"id":398,"name":"트리플러스 비타민C1000","brand":null},
{"id":399,"name":"트리플러스 비타민C1000(수출용)","brand":null},
{"id":400,"name":"트리플러스 한정판","brand":null},
{"id":401,"name":"트리플러스+","brand":null},
{"id":402,"name":"트리플러스10C","brand":null},
{"id":403,"name":"트리플러스50+","brand":null},
{"id":404,"name":"트리플러스50+액티브","brand":null},
{"id":405,"name":"트리플러스액티브","brand":null},
{"id":406,"name":"트리플루테인골드","brand":null},
{"id":407,"name":"트리플바이오틱스","brand":null},
{"id":408,"name":"트리플뷰티","brand":null},
{"id":409,"name":"트리플블럭 가르시니아","brand":null},
{"id":410,"name":"트리플비","brand":null},
{"id":411,"name":"트리플비타민C1000","brand":null},
{"id":412,"name":"트리플비프로폴리스캡슐","brand":null},
{"id":413,"name":"트리플센스앤바디","brand":null},
{"id":414,"name":"트리플스킨다이어트","brand":null},
{"id":415,"name":"트리플스트랭스 오메가3+코엔자임Q10","brand":null},
{"id":416,"name":"트리플써클케어","brand":null},
{"id":417,"name":"트리플액션","brand":null},
{"id":418,"name":"트리플액션데일리밸런스","brand":null},
{"id":419,"name":"트리플액티브","brand":null},
{"id":420,"name":"트리플엑셀다이어트","brand":null},
{"id":421,"name":"트리플엑스 127","brand":null},
{"id":422,"name":"트리플-엑스칼슘","brand":null},
{"id":423,"name":"트리플엔","brand":null},
{"id":424,"name":"혈당에 좋은 당애[愛]프리미엄","brand":null},
{"id":425,"name":"혈당에 좋은 바나바","brand":null},
{"id":426,"name":"혈당에좋은 당애(愛)","brand":null},
{"id":427,"name":"혈당엔 글루오프","brand":null},
{"id":428,"name":"혈당컨트롤 디비-1","brand":null},
{"id":429,"name":"혈당컷","brand":null},
{"id":430,"name":"혈당케어웰","brand":null},
{"id":431,"name":"혈당프로","brand":null},
{"id":432,"name":"혈류본골드","brand":null},
{"id":433,"name":"혈류신통","brand":null},
{"id":434,"name":"혈서보 (血舒宝)","brand":null},
{"id":435,"name":"혈시아 1000","brand":"동국제약"},
{"id":436,"name":"혈압 감소에 도움을 줄 수 있는 콘트롤","brand":null},
{"id":437,"name":"혈압 솔루션","brand":null},
{"id":438,"name":"혈압N코엔자임Q","brand":null},
{"id":439,"name":"혈압메이트","brand":null},
{"id":440,"name":"혈압엔멀티팩","brand":null},
{"id":441,"name":"혈압이 높은 사람에게 도움을 줄수있는 혈압케어","brand":null},
{"id":442,"name":"혈압케어","brand":"풀무원건강생활"},
{"id":443,"name":"혈이튼튼","brand":null},
{"id":444,"name":"혈천","brand":null},
{"id":445,"name":"혈천골드","brand":null},
{"id":446,"name":"혈청III 당바이오","brand":"SK 케미칼"},
{"id":447,"name":"혈통120","brand":null},
{"id":448,"name":"혈통원 프리미엄","brand":null},
{"id":449,"name":"혈행 솔루션","brand":null},
{"id":450,"name":"혈행 케어솔루션","brand":null},
{"id":451,"name":"혈행N멀티팩","brand":null},
{"id":452,"name":"혈행개선","brand":null},
{"id":453,"name":"혈행개선 솔루션","brand":null},
{"id":454,"name":"혈행개선앤혈행정","brand":null},
{"id":455,"name":"혈행개선에 도움을 주는 수협 혈행플러스","brand":null},
{"id":456,"name":"혈행개선에 도움을 주는 씨쓰리지캡슐","brand":null},
{"id":457,"name":"혈행개선에 도움을 줄 수 있는 프로그램","brand":null},
{"id":458,"name":"혈행개선에 도움을 줄 수 있는 혈행원","brand":null},
{"id":459,"name":"혈행개선엔 혜민정","brand":null},
{"id":460,"name":"혈행개선을 위한 은행잎","brand":null},
{"id":461,"name":"혈행건강 센 징코","brand":null},
{"id":462,"name":"혈행건강 오메가3 골드","brand":null},
{"id":463,"name":"혈행건강온","brand":null},
{"id":464,"name":"혈행다행 나이젠 나토키나제","brand":null},
{"id":465,"name":"혈행단","brand":null},
{"id":466,"name":"혈행마스터오메가-3","brand":null},
{"id":467,"name":"혈행메이트","brand":null},
{"id":468,"name":"혈행백(Back)","brand":null},
{"id":469,"name":"혈행쌩쌩","brand":null},
{"id":470,"name":"혈행에 좋은 오메가3","brand":null},
{"id":471,"name":"혈행에 좋은 오메가3 500","brand":null},
{"id":472,"name":"혈행에 좋은 오메가3 600","brand":null},
{"id":473,"name":"혈행에 좋은 오메가Q","brand":null},
{"id":474,"name":"혈행에통","brand":null},
{"id":475,"name":"혈행튼튼순수오메가3","brand":null},
{"id":476,"name":"혈행팔팔 DHA팔팔","brand":null},
{"id":477,"name":"혜간원","brand":null},
{"id":478,"name":"혜간원 환","brand":null},
{"id":479,"name":"혜당건생환","brand":null},
{"id":480,"name":"혜당메모리","brand":null},
{"id":481,"name":"혜당면역에이스ACE","brand":null},
{"id":482,"name":"혜당엔 백세환플러스","brand":null},
{"id":483,"name":"혜당엔 생기환","brand":null},
{"id":484,"name":"혜민환","brand":null},
{"id":485,"name":"혜수인","brand":null},
{"id":486,"name":"혜인담 홍삼정스틱","brand":null},
{"id":487,"name":"혜인담 홍삼차","brand":null},
{"id":488,"name":"혜지원타브렛골드(수출용)","brand":null},
{"id":489,"name":"호간생","brand":null},
{"id":490,"name":"호간원","brand":null},
{"id":491,"name":"호간위","brand":null},
{"id":492,"name":"호감","brand":null},
{"id":493,"name":"호관원 프리미엄","brand":null},
{"id":494,"name":"호관정","brand":null},
{"id":495,"name":"호관정프리미엄","brand":null},
{"id":496,"name":"호리호리 하이킥","brand":null},
{"id":497,"name":"홀리스틱G120","brand":null},
{"id":498,"name":"홀리스틱G120 (전량수출용)","brand":null},
{"id":499,"name":"홀리호리더블버닝다이어트","brand":null},
{"id":500,"name":"홀림","brand":null},
{"id":501,"name":"홀인원","brand":null},
{"id":502,"name":"홀푸드과일허브멀티비타민미네랄","brand":null},
{"id":503,"name":"홀핏 잔티젠 다이어트","brand":null},
{"id":504,"name":"홈런생(生)","brand":null},
{"id":505,"name":"홈런의 전설 오리지날","brand":null},
{"id":506,"name":"홈런의전설","brand":null},
{"id":507,"name":"홈스테인비타민정","brand":null},
{"id":508,"name":"홈스픽 프리바이오틱스 플러스+","brand":null},
{"id":509,"name":"홈플러스 오메가3","brand":null},
{"id":510,"name":"홈플러스 홍삼과 프로바이오틱스","brand":null},
{"id":511,"name":"홉킨스킴멜 식이섬유파워","brand":null},
{"id":512,"name":"홉킨스킴멜식이섬유파워","brand":null},
{"id":513,"name":"홍(紅)관절","brand":null},
{"id":514,"name":"홍(紅)오메가-3","brand":null},
{"id":515,"name":"홍.담.소(紅.談.笑)","brand":null},
{"id":516,"name":"홍간원","brand":null},
{"id":517,"name":"홍경천","brand":null},
{"id":518,"name":"홍경천 밀크씨슬 리프레쉬 더블","brand":null},
{"id":519,"name":"홍경천 밀크씨슬 프리미엄","brand":null},
{"id":520,"name":"홍경천 알파","brand":null},
{"id":521,"name":"홍경천 정제","brand":null},
{"id":522,"name":"홍경천 프로폴리스","brand":null},
{"id":523,"name":"홍경천(수출용)","brand":null},
{"id":524,"name":"홍경천베가사랑","brand":null},
{"id":525,"name":"홍경천추출농축액","brand":null},
{"id":526,"name":"홍경천프로폴리스","brand":null},
{"id":527,"name":"홍경천프리미엄","brand":null},
{"id":528,"name":"홍관절 프리미엄","brand":null},
{"id":529,"name":"홍교정로얄(수출용)","brand":null},
{"id":530,"name":"홍국","brand":null},
{"id":531,"name":"홍끼와 홍삼요정","brand":null},
{"id":532,"name":"홍담소","brand":null},
{"id":533,"name":"홍담소골드","brand":null},
{"id":534,"name":"홍디본플러스","brand":null},
{"id":535,"name":"홍루테인(수출용)","brand":null},
{"id":536,"name":"홍마정","brand":null},
{"id":537,"name":"홍박사 플러스","brand":null},
{"id":538,"name":"홍박사플러스","brand":null},
{"id":539,"name":"홍빚단","brand":null},
{"id":540,"name":"홍사랑","brand":null},
{"id":541,"name":"홍산도발효홍삼","brand":null},
{"id":542,"name":"홍삼 612 스텝1","brand":null},
{"id":543,"name":"홍삼 612 스텝2","brand":null},
{"id":544,"name":"홍삼 612 스텝3","brand":null},
{"id":545,"name":"홍삼 G-웰(Well)","brand":null},
{"id":546,"name":"홍삼 가득담은 6년근 골드스틱","brand":null},
{"id":547,"name":"홍삼 가득담은 6년근 골드스틱 플러스","brand":null},
{"id":548,"name":"홍삼 가득담은 6년근 젤리스틱","brand":null},
{"id":549,"name":"홍삼 꾸미","brand":null},
{"id":550,"name":"홍삼 서향 진액 眞","brand":null},
{"id":551,"name":"홍삼 세븐 (Red Ginseng Seven/7)","brand":null},
{"id":552,"name":"홍삼 스마트 플러스","brand":null},
{"id":553,"name":"홍삼 씨케이 플러스","brand":null},
{"id":554,"name":"홍삼 에이플러스업","brand":null},
{"id":555,"name":"홍삼 자운 순액 眞","brand":null},
{"id":556,"name":"홍삼 젤리스틱","brand":null},
{"id":557,"name":"홍삼 주니어스틱","brand":null},
{"id":558,"name":"홍삼 퀸스틱","brand":null}
]


export default function handler(req, res) {
  res.status(200).json(mockData);
};
